### ISSUE TITLE
Add support for iLO3 and iLO4 (HP)

### ISSUE THREAD

**Issue by Solvik** [PaulMaddox/drac-kvm#14]
It would be awesome to add the support for iLO3 and iLO4 too!

**Comment by Mudpuppy12** [comment]
The HP hardware would be a welcome addition

**Comment by Solvik** [comment]
I have a working example with iLO4, will submit it as a PR for review
@PaulMaddox are you still maintaining the project so you can comment my code ?

**Comment by Solvik** [comment]
Well, I pushed the PR on https://github.com/rockyluke/drac-kvm which seems to be the new maintained repository

**Comment by PaulMaddox** [comment]
Great to see someone else has forked this. I've worked at AWS for the last couple of years so DRAC seems like a distant memory...

I'll close this, and update the README to point to the new fork.
